import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { io } from "socket.io-client";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([]);

  const socket = io(`http://localhost:3000`);

  useEffect(() => {
    socket.on("receiveMessage", (msg) => {
      receiveMessage(msg);
    });

    // socket.on("getMessages", (message) => {
    //   console.log('messages from socket =>', message);

    //   // const newMessage = [];
    //   // newMessage.push(notification);
    //   // console.log('these are the posts from socket 2 =>', newMessage);
    //   // const posts = newMessage[0];
    //   // console.log("updated__posts_from_server ::", posts);
    //   // setSocketNotifications(posts);
    //   // setSocketNotifications((pre) => [...pre, ...notification]);
    // });

    getInitialMessages();
  }, []);

  function getInitialMessages() {
    fetch("http://localhost:3000/messages")
      .then((res) => res.json())
      .then((data) => {
        console.log("data from fetch ::", data);
        setMessages(data);
      });
  }

  function receiveMessage(msg) {
    console.log("Message from Socket ::", msg, "message length ::", messages.length);
    const newMessages = [...messages, msg];
    setMessages(newMessages);
  }

  const handleInputChange = (event) => {
    setMessage(event.target.value);
  };

  function sendMessage() {
    socket.emit("sendMessage", message);
    setMessage("");
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <script src="../scripts/verxid.js"></script> */}
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <input
              type="text"
              value={message}
              name="content"
              onChange={handleInputChange}
              className="form-control"
            />
            <button className="btn btn-primary" onClick={sendMessage}>
              Send
            </button>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          {console.log("messages ::", messages)}
          <div key={message.id}>
            <ul>
              {messages.map((message) => (
                <li style={{ color: "#fff" }}>{message.content}</li>
              ))}
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
